export const mainLines = [
  ['ennukee'],
  ['profession', 'full-stack software engineer'],
  ['company', 'google quantum ai'],
  ['past roles', 'google health ai, vestmark'],
  [],
  ['tech.stack.web', 'react, nextjs, vite, js, ts, css, sass'],
  ['', 'emotionjs, styled components, react native'],
  ['tech.stack.backend', 'nodejs, python, express/fastify, git'],
  ['', 'jenkins, atlassian, docker, cypress'],
  ['', 'digitalocean, java, kotlin'],
  [],
  ['interests', 'gaming, AI, digital culture, media,'],
  ['', 'interactive animated media (vtubing, etc)'],
  ['about'],
  ['about me', 'hey there! i\'m dylan, a software engineer based in the'],
  ['', 'united states. all of my professional work is for'],
  ['', 'proprietary systems, so please understand i cannot'],
  ['', 'disclose specifics. however, most of my personal'],
  ['', 'projects are in public repos on github!'],
  ['my work', 'i build all kinds of things, but professionally focus'],
  ['', 'on data-heavy full stack web applications, utilizing'],
  ['', 'primarily javascript web frameworks and a variety of'],
  ['', 'backend tech stacks'],
  ['contact'],
  ['email', 'dylanvolibowers@gmail.com'],
  ['linkedin', 'dylan-bowers'],
  ['twitter', 'priestismjp'],
  ['discord', 'ennukee'],
]

// dont ask
export const mainLinesValueColors = [
  -1,
  0, 1, 0,
  -1,
  1, 1,
  0, 0, 0,
  -1,
  1, 1,
  -1,
  0, 0, 0, 0, 0,
  1, 1, 1, 1,
  -1,
  0, 1, 0, 1,
]